modLoader="javafml" #mandatory
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
[[mods]] #mandatory
modId="prehistoricfauna" #mandatory
version="2.0.0" #mandatory
displayName="Prehistoric Fauna" #mandatory
credits="AGSuko, Antlion, Bastion, Baular, Coda, Corgi Taco, Obsolerus, RafaMv, Ralof, Seal, superlord9362, Weastian" #optional
authors="superlord9362, Corgi Taco, RafaMv" #optional
description='''
Travel to the past to discover worlds time forgot. Bring back animals long extinct, or join their world.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.prehistoricfauna]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31.2.50,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"